global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
  #- "first_rule.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['165.22.50.178:9100']
  - job_name: 'rabbitmq'
    static_configs:
    - targets: ['165.22.50.178:9419']