global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  #- "first_rule.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
    